require('options')
vim.g.racket_hash_lang_dict = { ['simply-scheme'] = 'racket' }
require('lazy-config')
require('colors')
require('treesitter-config')
require('null-ls-config')
require('lsp-config.language-servers')
require('cmp-config')
require('neorg-config')
require('telescope-config')
require('alpha-config')
require('dial-config')
require('luasnip-config')
require('neo-minimap-config')
require('oil-config')
require('ts-rainbow-config')
require('which-key-config')
require('keybindings')
