require('options')
require('lazy-config')
require('colors')
require('treesitter-config')
require('mason-config')
require('lsp-config.language-servers')
require('cmp-config')
require('neorg-config')
require('telescope-config')
require('alpha-config')
require('dial-config')
require('luasnip-config')
require('null-ls-config')
require('neo-minimap-config')
require('oil-config')
require('ts-rainbow-config')
require('mappings')
require('mappings')
-- vim.g["aniseed#env"] = { module = "init", compile = true }
-- require('aniseed.env').init()
